<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Cucumber" time="18.36" tests="15" skipped="0" failures="7" errors="0">
<testcase classname="Main Functionality Tests for Calculator" name="Validate addition on calculator - Example #1.1" time="1.677">
<failure type="org.opentest4j.AssertionFailedError" message="expected: &lt;5&gt; but was: &lt;6&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: expected: <5> but was: <6>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:551)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 5 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:15)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user add the following "5".........................................passed
Then verify the 5 is as expected............................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate addition on calculator - Example #1.2" time="1.187">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user add the following "2, 3"......................................passed
Then verify the 5 is as expected............................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate addition on calculator - Example #1.3" time="1.205">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user add the following "3, 4, 0"...................................passed
Then verify the 7 is as expected............................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate addition on calculator - Example #1.4" time="1.249">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user add the following "1, 2, 9, 8"................................passed
Then verify the 20 is as expected...........................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate addition on calculator - Example #1.5" time="1.241">
<failure type="org.opentest4j.AssertionFailedError" message="expected: &lt;10&gt; but was: &lt;0&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: expected: <10> but was: <0>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:551)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 10 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:15)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user add the following "0, 0, 4, 4, 2".............................passed
Then verify the 10 is as expected...........................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate subtraction on calculator - Example #1.1" time="1.146">
<failure type="java.lang.NumberFormatException" message="For input string: &quot;-&quot;">
<![CDATA[java.lang.NumberFormatException: For input string: "-"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.valueOf(Integer.java:999)
	at Pages.MainPage.getResult(MainPage.java:72)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 0 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:27)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user substracts the following "1, 1"...............................passed
Then verify the 0 is as expected............................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate subtraction on calculator - Example #1.2" time="1.196">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user substracts the following "2, 3"...............................passed
Then verify the -1 is as expected...........................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate subtraction on calculator - Example #1.3" time="1.203">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user substracts the following "9, 6, 2"............................passed
Then verify the 1 is as expected............................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate multiplication on calculator - Example #1.1" time="1.174">
<failure type="org.opentest4j.AssertionFailedError" message="expected: &lt;1&gt; but was: &lt;3&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: expected: <1> but was: <3>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:551)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 1 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:37)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user multiplies the following "1, 1"...............................passed
Then verify the 1 is as expected............................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate multiplication on calculator - Example #1.2" time="1.126">
<failure type="org.opentest4j.AssertionFailedError" message="expected: &lt;4&gt; but was: &lt;6&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: expected: <4> but was: <6>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:551)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 4 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:37)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user multiplies the following "2, 2"...............................passed
Then verify the 4 is as expected............................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate multiplication on calculator - Example #1.3" time="1.212">
<failure type="org.opentest4j.AssertionFailedError" message="expected: &lt;336&gt; but was: &lt;354&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: expected: <336> but was: <354>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:551)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 336 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:37)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user multiplies the following "6, 7, 8"............................passed
Then verify the 336 is as expected..........................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate multiplication on calculator - Example #1.4" time="1.208">
<failure type="org.opentest4j.AssertionFailedError" message="expected: &lt;24&gt; but was: &lt;58&gt;">
<![CDATA[org.opentest4j.AssertionFailedError: expected: <24> but was: <58>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:551)
	at StepDefinitions.CalcStepDefs.verifyTheResultIsAsExpected(CalcStepDefs.java:27)
	at ✽.verify the 24 is as expected(file:///Users/bilal/IdeaProjects/CalculatorApp/src/test/resources/Features/demo.feature:37)
]]>
</failure>
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user multiplies the following "1, 2, 3, 4".........................passed
Then verify the 24 is as expected...........................................failed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate division on calculator - Example #1.1" time="1.132">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user divides the following "0, 6"..................................passed
Then verify the 0 is as expected............................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate division on calculator - Example #1.2" time="1.181">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user divides the following "4, 2"..................................passed
Then verify the 2 is as expected............................................passed
]]></system-out>
</testcase>
<testcase classname="Main Functionality Tests for Calculator" name="Validate division on calculator - Example #1.3" time="1.131">
<system-out><![CDATA[
Given the user is on the calculator.........................................passed
When the user divides the following "9, 3"..................................passed
Then verify the 3 is as expected............................................passed
]]></system-out>
</testcase>
</testsuite>
